// Generated by scripts/build-zh-tw-dictionary.mjs. Do not edit manually.

export const ZH_TW_TECH_DICTIONARY_VERSION = "zh-tw-tech-v1";
export const ZH_TW_TECH_DICTIONARY_SHA256 = "24979c959b05e44f7912ee00e1cbd4ea18d30abc74301e8ed35b18c06140f5d8";
export const ZH_TW_TECH_DICTIONARY_TERMS = [
  "二元樹",
  "人工智慧",
  "介面",
  "伺服器",
  "佇列",
  "位元組",
  "原始程式碼",
  "呼叫",
  "命令列",
  "回呼",
  "執行緒",
  "堆疊",
  "字串",
  "布林",
  "快取",
  "演算法",
  "物件",
  "用戶端",
  "相依性",
  "硬碟",
  "程式碼",
  "網際網路",
  "記憶體",
  "資料夾",
  "資料庫",
  "軟體",
  "遞迴",
  "鏈結串列",
  "陣列",
  "雜湊",
  "非同步",
  "預設"
] as const;
export const ZH_TW_TECH_DICTIONARY_TEXT = "二元樹 1000000 nz\n人工智慧 1000000 nz\n介面 1000000 nz\n伺服器 1000000 nz\n佇列 1000000 nz\n位元組 1000000 nz\n原始程式碼 1000000 nz\n呼叫 1000000 nz\n命令列 1000000 nz\n回呼 1000000 nz\n執行緒 1000000 nz\n堆疊 1000000 nz\n字串 1000000 nz\n布林 1000000 nz\n快取 1000000 nz\n演算法 1000000 nz\n物件 1000000 nz\n用戶端 1000000 nz\n相依性 1000000 nz\n硬碟 1000000 nz\n程式碼 1000000 nz\n網際網路 1000000 nz\n記憶體 1000000 nz\n資料夾 1000000 nz\n資料庫 1000000 nz\n軟體 1000000 nz\n遞迴 1000000 nz\n鏈結串列 1000000 nz\n陣列 1000000 nz\n雜湊 1000000 nz\n非同步 1000000 nz\n預設 1000000 nz\n";
export const ZH_TW_TECH_DICTIONARY_BYTES = new TextEncoder().encode(ZH_TW_TECH_DICTIONARY_TEXT);
